### ISSUE TITLE
Error if enter the wrong code

### ISSUE THREAD

**Issue by matata86** [kukulich/home-assistant-jablotron100#10]
Hi, thanks a lot for integrating the jablotron into the Home Assistant ... It's great. I just have this problem - if I want to secure and enter the wrong code, the sensor will change to unsecured. Jablotron remains properly secured, but HA incorrectly reports that it is unsecured.

**Comment by kukulich** [comment]
It will be improved in version 3.0.0

The new behaviour:
- The section state changes to "unsecured"
- After a few seconds the state changes back to "secured"

This is better for the user when the right code is inserted. The UI can response immediately.
