### ISSUE TITLE
Jablotron integration not loaded after HA start. 

### ISSUE THREAD

**Issue by DorwinDT** [kukulich/home-assistant-jablotron100#101]
I have strange issue with jablotron integration. Homeassistant I have on Esxi and after starting of virtual machine with HA sometimes Jablotron didn't start. I have to go to settings and manually reload integration.
Did someone notice that?
Or is it possible to do it automatically either in node red  or automation? 
Thank you for help.

**Comment by jaeuwi74** [comment]
Same for me on proxmox vm

**Comment by kukulich** [comment]
It's probably problem in your HA installation.
