### ISSUE TITLE
When USB device is disconnected, /dev/hidraw0 is created by the integration

### ISSUE THREAD

**Issue by andyboeh** [kukulich/home-assistant-jablotron100#103]
Sometimes, I have to disconnect the USB cable. Whenever this happens, the integration still tries to read/write from the hidraw device, resulting in a new file being created (hidraw1 in this case):
```
crw------- 1 root root 246, 0 Oct  5 00:24 /dev/hidraw0
-rw-r--r-- 1 root root      9 Oct  7 01:09 /dev/hidraw1
```
When the device is reconnected, the kernel assigns hidraw1 again, but the node can't be created due to the existing file and I'm stuck with a non-working integration until I manually delete the file.

Any chance this can be fixed?

**Comment by kukulich** [comment]
You can disable the integration just before you disconnect the cable.

I thnk it’s not the right solution to add another check to integretion because it can slow down the communication.

**Comment by kukulich** [comment]
> Why is the stream closed and reopened at all and not kept open?

It does not work without closing the stream.
