### ISSUE TITLE
Status of Section 1 is "Unknown" After upgrade to 2024.11.0

### ISSUE THREAD

**Issue by pszypowicz** [kukulich/home-assistant-jablotron100#106]
I did an upgrade of HA yesterday and today I see that the "Section 1" status is unknown:

![image](https://github.com/user-attachments/assets/8b95d7b4-0ae7-4278-b69b-7c6552a25828)

edit: I downgraded to a backup from before an upgrade and status of "Section 1" came back.

**Comment by jaeuwi74** [comment]
same for me

**Comment by pszypowicz** [comment]
I just want to confirm that the latest release works back. Thank you for such a quick fix!
