### ISSUE TITLE
HA is dead when JA is configured but not connected on start

### ISSUE THREAD

**Issue by tpazderka** [kukulich/home-assistant-jablotron100#13]
I had a JA unit configured (JA-106K) and after HA restart, the system decided to give it a different device address (from `hidraw0` to `hidraw1`) and the web interface was not starting at all. The uwsgi requests were timing out.  Nothing suspicious in the logs.

**Comment by RRobby** [comment]
Same for me :-( .  Often i solved disconnecting/reconnecting usb cable from Jablotron Controll unit , but I don't like this workaround. I just activated  logger (40 min ago) as suggested by @kukulich on other tread but as soon as restarted ... everything started to go again.

**Comment by lukinno1** [comment]
I have the same problem. Do you have solution?

Lukas

**Comment by kukulich** [comment]
Try to enable debug mode: https://github.com/kukulich/home-assistant-jablotron100#debugging

**Comment by lukinno1** [comment]
![image](https://user-images.githubusercontent.com/69607462/156020952-5a86d07a-563a-4978-888e-215690edc371.png)

**Comment by lukinno1** [comment]
I need remove integration always after remove cable and again connect.

**Comment by kukulich** [comment]
@lukinno1 It should not be necessary. Only HaOS restart should be enough.
