### ISSUE TITLE
Possibility to change sensor type

### ISSUE THREAD

**Issue by tpazderka** [kukulich/home-assistant-jablotron100#14]
Is there any possibility to change the sensor type? I have missed a row and added one device as motion detector instead of window detector and now it has wrong icon/states.

I have tried to change that it the entity_registry configuration but the changes do not take effect and are always overwritten.

**Comment by kukulich** [comment]
@tpazderka You can change it in .storage/.config.entries (or something like this)

**Comment by tpazderka** [comment]
Tried that, but the class changes back on server start. I have tried to change the class on running system and even on stopped system, but no luck.

**Comment by kukulich** [comment]
@tpazderka You probably modified something else. There’s configuration of the integration in the file mentioned above.

**Comment by tpazderka** [comment]
OK, finally managed to find the correct location... I was changing the class of the device in `.storage/core.entity_registry` and not in `.storage/core.config_entries`.
