### ISSUE TITLE
Factor out Jablotron protocol into separate library

### ISSUE THREAD

**Issue by andyboeh** [kukulich/home-assistant-jablotron100#15]
I just stumbled upon this interesting project because I would like to integrate my JA-106K into Domoticz. I've already done a cloudless implementation by simulating a SIA ARC, but this only works one-way and only if myJablotron is not used.

It would help a lot if we could implement the Jablotron-specific part in a library and then have a glue-layer for Domoticz and HA. I can have a look into this in the next few days/weeks, but I can only do the Domoticz glue, not the HA glue.

Do you think that makes sense and can be done with a reasonable amount of work?

**Comment by kukulich** [comment]
I'm sorry but creating standalone Jablotron library will just make my programming more complicated so I'm not interested. I'm also not sure if it's even possible. It looks that Domoticz is in C++ but HA is in Python.

**Comment by andyboeh** [comment]
OK, thanks for the quick response.
Domoticz is in C++, but Python plugins are supported and work very well.
