### ISSUE TITLE
Missing "*" key on alarm panel

### ISSUE THREAD

**Issue by RiodaITA** [kukulich/home-assistant-jablotron100#17]
With the last update, the integration accept codes containing "*" but the alarm panel "keyboard" does not have this symbol so it's not possible to digit the correct code to turn on or off the alarm.

**Comment by kukulich** [comment]
The numeric keypad is removed completly when code contains asterisk - in release 3.1.2.

**Comment by RiodaITA** [comment]
Well done and thank you very much for your great work, I'm not a programmer
so I can't help but offering me to translate to Italian if you are
intersted.

Kind regards

Luca Rodella

Il mer 6 gen 2021, 09:00 Jaroslav Hanslík <notifications@github.com> ha
scritto:

**Comment by kukulich** [comment]
@RiodaITA perfect! It’s easy. Just translate this file: https://github.com/kukulich/home-assistant-jablotron100/blob/master/custom_components/jablotron100/translations/en.json

**Comment by RiodaITA** [comment]
Hi Jaroslav,

I proposed the new file on github, this is the first time I use this tool
so probably I did it in the wrong way, please just let me know.

Bye!

Il giorno mer 6 gen 2021 alle ore 19:14 Jaroslav Hanslík <
notifications@github.com> ha scritto:
