### ISSUE TITLE
Support for JA100K?

### ISSUE THREAD

**Issue by LukasVice** [kukulich/home-assistant-jablotron100#18]
Is there a way to support the JA100K or does it miss some functionality?
Thank you!

**Comment by kukulich** [comment]
@LukasVice we don’t know - you have to try :) It would be easier if you join the Discord

**Comment by LukasVice** [comment]
OK, I'll join the Discord!

FYI: I changed the regular expression in jablotron.py and it seems to work with JA100K!

https://github.com/kukulich/home-assistant-jablotron100/blob/836045ab9d9baa58b34c11703c98e23fe975706e/custom_components/jablotron100/jablotron.py#L176

**Comment by kukulich** [comment]
Support released in 3.2.0.

**Comment by LukasVice** [comment]
I have it in use for a few days now and everything works fine! Thanks for your great work!
