### ISSUE TITLE
Při chybném kódu stále bliká "zabezpečuji"

### ISSUE THREAD

**Issue by matata86** [kukulich/home-assistant-jablotron100#20]
Ahoj, chtěl jsem vyzkoušet event při zadání chybého pinu. Event funguje perfektně, ale při zadání chybného kódu stále bliká u sekce že zabezpečuje. Je to jen u sekce kde je nastaveno zpožděné odchodové zabezpečení.

Pamatuji si že stejný problém byl u jedné z prvních verzí, pak to bylo opraveno, ale ted je to tu zas. Děkuji moc.

![Peek 2021-02-19 11-03](https://user-images.githubusercontent.com/28623294/108494988-810b3680-72a8-11eb-8009-d0ffc9b1e77c.gif)

**Comment by kukulich** [comment]
@matata86 Zadáváš kód, který má aspoň 4 znaky, nebo méně?

**Comment by matata86** [comment]
Ano, zadávám přesně 4 znaky chybneho kodu a stále bliká zabezpečuji.

**Comment by kukulich** [comment]
@matata86 Zkus prosím dev verzi: https://github.com/kukulich/home-assistant-jablotron100

**Comment by matata86** [comment]
Dev verze funguje korektně.

**Comment by kukulich** [comment]
Vydán release 3.3.1
