### ISSUE TITLE
Possibility to add new devices?

### ISSUE THREAD

**Issue by andyboeh** [kukulich/home-assistant-jablotron100#22]
I installed a few new devices on the bus, how can I add them to the integration? Is the only chance editing the configuration files in `.storage`? If yes, how is the `id` generated or where is it read from?

**Comment by kukulich** [comment]
@andyboeh

1. You can remove the integration and install it again, entities IDs should be preserved - if the new devices are at the end of the list

2. You can add the devices to the list in config/.storage/config.config_entitries

**Comment by andyboeh** [comment]
>     2\. You can add the devices to the list in config/.storage/config.config_entitries

Thank you, that works perfectly fine! I didn't know that the entities are then created automatically. The exact steps are:

  1. Edit `config/.storage/core.config_entries`
  2. Find the section with domain `jablotron100`
  3. Change `"number_of_devices"` to match the new number of devices
  4. Add the new/changed device types to the `devices` array
