### ISSUE TITLE
service not found error

### ISSUE THREAD

**Issue by benp09** [kukulich/home-assistant-jablotron100#23]
I have 2 HA instances, on running on a Pi and one in a VM. They are connected via Remote HA. I have the Pi connected via usb to the Jablotron system and that works fine. All the entities of Jablatron are also available on the VM (via remote HA), all status reading works fine but trying to send a command (arm) fails with a service not found error (works on the Pi but not on the VM). Any idea's on how to fix this?

**Comment by kukulich** [comment]
I’m sorry I don’t use “Remote HA”.
