### ISSUE TITLE
No version key in the manifest file

### ISSUE THREAD

**Issue by DarkWarden85** [kukulich/home-assistant-jablotron100#25]
Hi,

I have just successfully integrated my Jablotron System in Home Assistant thanks to this awesome integration. Everything works fine. I only get the followig warning in the logs:

**Logger: homeassistant.loader
Source: loader.py:802
First occurred: 5:13:42 PM (1 occurrences)
Last logged: 5:13:42 PM

No 'version' key in the manifest file for custom integration 'jablotron100'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'jablotron100'**

Custom integrations without version key in their manifest file while apparently stop working in June this year.
Could this key please be added to keep this integration working?

Kind regards

**Comment by kukulich** [comment]
It’s already solved in master. I just did not release it.

**Comment by DarkWarden85** [comment]
Thanks a bunch! What a quick response time!
