### ISSUE TITLE
Adding integration aborted

### ISSUE THREAD

**Issue by vojtechalbl** [kukulich/home-assistant-jablotron100#26]
Hi,

I am running Home Assistant 2021.3.4 in docker on openmediavault 5.

The cable is located on:

 dmesg | grep hid
[    1.504233] hid: raw HID events driver (C) Jiri Kosina
[    1.513705] usbcore: registered new interface driver usbhid
[    1.513720] usbhid: USB HID core driver
[    1.518085] hid-generic 0003:16D6:0008.0001: hiddev0,hidraw0: USB HID v1.11 Device [Jablotron ltd JA-100 Flexi] on usb-0000:00:14.0-6/input0

When I am trying to add integration to Home Assistant, I am getting following error:

Logger: custom_components.jablotron100
Source: custom_components/jablotron100/config_flow.py:89
Integration: jablotron100 (documentation, issues)
First occurred: 7:06:54 PM (4 occurrences)
Last logged: 7:30:55 PM

Unknown error connecting to Jablotron at /dev/hidraw0

Any suggestions, please...

**Comment by jeanpijon** [comment]
I have the same issue, any help?

**Comment by gustavsingh** [comment]
Same issue here.
