### ISSUE TITLE
Possibility to trigger alarm from HA to make it ring

### ISSUE THREAD

**Issue by andgest** [kukulich/home-assistant-jablotron100#27]
Hello,
Firstly thank you for your job.
The integration of Jablotron work perfectly for me :)
But I wonder if it's possible to trigger the alarm from home assistant to make it ring when the alarm is armed ?
I tried to change the state of the alarm entity or jablotron motion sensor, but the change of state is not propagate to Jablotron.
I ask this because I want to add some additional security devices (door sensors, cameras) on my home assistant to improve the Jablotron security system and benefit from the jablotron siren and SMS notification system.
Thank you for your answer :)

**Comment by kukulich** [comment]
No, we did not find any way how to trigger the alarm :(

**Comment by Shamshala** [comment]
There still is an option of adding a switch to one of the Jablotron inputs though... :slightly_smiling_face:

**Comment by andgest** [comment]
@kukulich It's sad, it would have been perfect ^^'

@Shamshala I didn't quite understand your solution. Can you explain a little more in detail :)

**Comment by Shamshala** [comment]
@andgest Using a switch(Sonoff/Tuya/ESP based board with alternative firmware) connected to one of Jablotron potential-free inputs. You won't be able to tell exactly which sensor from HA triggered it but still better than nothing.

**Comment by andgest** [comment]
@Shamshala If I understand correctly you said that it's possible to pair a non jablotron device with jablotron system by changing the firmware of the device to make it compatible with.
Then Home Assistant could change the state of this device directly (without passing by kukulich integration) that propagate the change to Jablotron and make the alarm ring.
Like if the device become a bridge between HA and Jablotron (work with both system, pair with both system) ?
That's it ?
There is some article / blog / github that talk more about this way to do (what device to choose, what custom firmware to applied) ?
Or it's a theorical proposal that should work but I need to develop my own firmware 🥴 ?
Thank you for your reply :)

**Comment by kukulich** [comment]
It’s also probably possible to use PG output that’s set to trigger alarm.

**Comment by andyboeh** [comment]
I just did something like that: I acquired a JA-114HN Input/Output module and connected it (via an opto-isolator) to an Arduino Nano. The Nano is connected to the server running Home Assistant via USB and is running the Firmata firmware. Using the firmata integration, I can easily trigger an alarm on the Jablotron and also react to PG outputs.

**Comment by andgest** [comment]
> It’s also probably possible to use PG output that’s set to trigger alarm.

Hello,
I tried today to see if it was possible to trigger the alarm via a PG output (or enable panic mode), but after 1 hour of trying I gave up.
Maybe it's me who doesn't know how to use F-Link (J-Link) :(
It's not so good compared to Home Assistant :D
Any idea ?

**Comment by andgest** [comment]
> I just did something like that: I acquired a JA-114HN Input/Output module and connected it (via an opto-isolator) to an Arduino Nano. The Nano is connected to the server running Home Assistant via USB and is running the Firmata firmware. Using the firmata integration, I can easily trigger an alarm on the Jablotron and also react to PG outputs.

Great!
However, unfortunately I think this solution will be beyond my abilities unless I have a step by step tutorial ^^'

**Comment by Shamshala** [comment]
@andgest Basically the board JA-114HN is what I meant.

You don't need anything fancy, just a "dumb" Jablotron input (not the bus based) to which you can connect any HA controllable board/box with a relay (or something else). Then in case of you are interested in triggering Jablotron from HA, you just need to send a command to whatever board you used (Sonoff, ESPhome, Tuya, etc.) and switch the contacts of JA-114HN together (which Jablotron will interpret as a sensor).

**Comment by andyboeh** [comment]
That's exactly what I did. Since my Jablotron central is next to my Home Assistant box, I wanted a wired solution. The Arduino Nano with the Firmata firmware can be used as generic input/output in Home Assistant. 
I connected optocouplers (CNY17-3 IIRC) to the Arduino outputs to drive the Jablotron inputs, the Jablotron outputs are directly connected to Arduino inputs. It's all inside the central box and looks like this:

![1024-1365](https://user-images.githubusercontent.com/3099753/130235731-109fe670-4da0-460d-8263-22cc6e747648.jpg)

I assigned groups of my Z-Wave smoke detectors to the Jablotron inputs, so I know roughly where the smoke was triggered.

**Comment by andgest** [comment]
Thank you for your explanations, the references and for the picture!
It seems much clearer to me now.
Electricity and especially electronics is not really my thing but I will look into making this.
The JA-114HN component seems complicated to get in France without going through an installer :/
It's about 110€ from what I've seen in other European countries, is that right?

**Comment by andyboeh** [comment]
Unfortunately, it's rather expensive. I looked for months in online market places until I found a used one.

**Comment by andgest** [comment]
Hello,
It just occurred to me that I could use a JA-150P wireless motion sensor to trigger the alarm by making it look like it has detected motion.
Unfortunately electronics is not my area of expertise...
Does anyone have any idea how to do this hack?
![Compress_20230712_154215_5797](https://github.com/kukulich/home-assistant-jablotron100/assets/7107471/778c696d-5c93-4298-a2fa-6cc6440c6b92)
![Compress_20230712_154216_6013](https://github.com/kukulich/home-assistant-jablotron100/assets/7107471/96e1f1c8-3556-4ff2-b60c-3f8e89bda61b)
![Compress_20230712_154216_6160](https://github.com/kukulich/home-assistant-jablotron100/assets/7107471/3ae05dc2-c3b7-478c-a81d-5ff6a8d604db)

**Comment by Shamshala** [comment]
Why would you choose to use PIR (motion) sensor instead of mere magnetic (window) sensor which is only two contacts you just need to bridge by a wire?

Btw there should be "temper" button in the PIR, so that's probably the easiest way to set it off.

**Comment by Shamshala** [comment]
Why would you choose to use PIR (motion) sensor over a mere magnetic (window) sensor which are only two contacts you just need to bridge by a wire?

Btw, there should be "tamper" button in the PIR, so that's probably the easiest way to set it off.

**Comment by andgest** [comment]
Thank you!!!

Indeed I just thought of this TAMPER button to trigger the alarm with a small robot that presses the button (example:
https://fr.aliexpress.com/item/1005005581081848.html?spm=a2g0o.order_list.order_list_main.10.59905e5bfa4nEp&gatewayAdapt=glo2fra) and it works :)

I wanted to do it with a device I already have
But actually using a sensor a magnetic door sensor is an economical alternative

**Comment by andgest** [comment]
Ok, even better, by shutting these two pins corresponding to the tamper butt
![IMG_20230712_161900](https://github.com/kukulich/home-assistant-jablotron100/assets/7107471/4e3bd8cb-e471-42d3-8477-566360fa45bf)
on

**Comment by Shamshala** [comment]
> Thank you!!!
> 
> Indeed I just thought of this TAMPER button to trigger the alarm with a small robot that presses the button (example:
> https://fr.aliexpress.com/item/1005005581081848.html?spm=a2g0o.order_list.order_list_main.10.59905e5bfa4nEp&gatewayAdapt=glo2fra) and it works :)
> 
> I wanted to do it with a device I already have
> But actually using a sensor a magnetic door sensor is an economical alternative

Ok, I thought about the bridging the tamper button pins on the PCB, not using a robot to press the button 😅. But you've figured it by yourself. Viva la DIY!
