### ISSUE TITLE
CO Detector JA-150G-CO

### ISSUE THREAD

**Issue by andyboeh** [kukulich/home-assistant-jablotron100#33]
I acquired some JA-150G-CO wireless modules for installation in Ei208 carbon monoxide detectors. I can't seem to get any information on them into home assistant - are they supported at all?

**Comment by kukulich** [comment]
@andyboeh Please connect us on Discord. We can talk there how you can help us to add the support.

**Comment by andyboeh** [comment]
OK, so it's currently unsupported. Sorry, I don't have Discord and I'm not going to join it.

**Comment by kukulich** [comment]
@andyboeh Yes, it's unsupported and it never will be supported without help.

**Comment by andyboeh** [comment]
Sorry, it's not about not wanting to help or being rude. It's about Discord and me not having the resources for synchronous communication and/or live debug sessions.

Anyway, the log file already contained state and info packets:
State packet: `55093308010ac5b6500b0d`
Info packet: `900b289c080a1eae0002000001`

**Comment by andyboeh** [comment]
Sorry, I'll close the issue again: I made a mistake during configuration, the JA-150G-CO is already supported and seems to be working perfectly fine.
