### ISSUE TITLE
Issue with configuration (number of devices)

### ISSUE THREAD

**Issue by mgmtotorsperformance** [kukulich/home-assistant-jablotron100#34]
Hi

Have issue with adding number of devices
In F-Link i can see 19 devices and 5 PG

I can add PG but cant add devices
i do have Installator and administrator code

both show unknown error, no matter how many devices i choose

LOG when i try do configuration with adding 19 devices

Ten błąd pochodzi z niestandardowej integracji.

Logger: custom_components.jablotron100
Source: custom_components/jablotron100/jablotron.py:1935
Integration: Jablotron 100 (documentation, issues)
First occurred: 19:04:01 (53 occurrences)
Last logged: 19:20:16

State packet of unknown device (device 6): 550801818001224f5309
State packet of unknown device (device 6): 550801818001824f7309
State packet of unknown device (device 6): 55080181800142509309
State packet of unknown device (device 6): 550801818001a250b309
State packet of unknown device (device 6): 5508018180010251d309

**Comment by kukulich** [comment]
Please post diagnostics (downloadable in HA)

**Comment by mgmtotorsperformance** [comment]
Can't download diagnostics from jablotron integration. Keep getting "Failed - Server problem". Tried in few software versions. Integration is working for arm and disarm all 3 zones I have but cant add all devices i have in system.

**Comment by kukulich** [comment]
The error "State packet of unknown device (device 6)" looks like you added only five devices (or less).

**Comment by kukulich** [comment]
We can solve it faster if you can join our Discord.

**Comment by kukulich** [comment]
Solved on Discord.
