### ISSUE TITLE
Jablotron - battery state issue

### ISSUE THREAD

**Issue by RRobby** [kukulich/home-assistant-jablotron100#35]
Good evening , 
I integrated my HA with my alarm system Jablotron JA-106K and all works like a charms ( sensors are ok ) but I noticed that unfortunatly I can't get battery states of wireless external sensors  and outdoor siren.
For example :

-Battery level of motion detector - entity ID : sensor.battery_level_of_motion_detector_device_29  - Status : Unavailable

-Battery level of outdoor siren - entity ID: sensor.battery_level_of_outdoor_siren_device_12 - Status: Restored

-Battery load voltage of outdoor siren (device 12) - entity ID : sensor.battery_load_voltage_of_outdoor_siren_device_12 - Status : Restored

Could you help me to solve this issue ? Is this type of check supported by integration ?
Actually I'm running latest version of HA and Jablotron integration too. (Screenshots in attach)
 
Thank you in advance for your precious helps
Roberto
![Battery_states](https://user-images.githubusercontent.com/44643774/155386498-415c809f-5594-449e-83d3-77817de61911.png)
![Jablotron_version](https://user-images.githubusercontent.com/44643774/155386503-9db0d5d7-a0ae-4a69-88bc-34022f6186b7.png)

**Comment by kukulich** [comment]
@RRobby you can tey debug:

1. First enable debug mode for jablotron integration via “logger” integration
2. enable debug in jablotron integration options

It should be enough to enabled only “Log all devices packets”

Try to log the debug for some time and then post it please.

**Comment by RRobby** [comment]
@kukulich
I Jaroslav ,thanks for your quick reply. I'm not so configend about log and debug on HA ...anyway
1. Refering to your fisrt point I inserted the follwing statements under my configuration.yaml , is it right ?
    logger:
     default: debug
    Obviously, after that I restarted HA
2. Refering to second point how to enable debug in Jablotron integration ?  I don't see  this options clicking on Jablotron 3 dots ( see screenshot)

Once activated , which is the repository of this logs?
Thanks
Roberto

![Jablotron_options](https://user-images.githubusercontent.com/44643774/155404382-1ebed1fa-1311-4985-b3d1-b6529fa62fa1.png)

**Comment by kukulich** [comment]
@RRobby you the “configure” - in your screenshot on bottom right

**Comment by RRobby** [comment]
@kukulich 

![Jablotron_configure](https://user-images.githubusercontent.com/44643774/155407807-3d7ac0b0-11e7-445c-9b0c-4c658d3c835b.png)
Hi, 
in "configure"  no debug options , I can insert only my alarm code , number of  devices and  PG; i used this button to configure initially all my 37 devices . If I enter them again I will have to remap them all.

**Comment by kukulich** [comment]
@RRobby just submit the form without any change. And the same for next form.

**Comment by RRobby** [comment]
@kukulich 
Ohhh , ok, perfect, just activated.
Let me know how long do I have to leave it on and where can I retrieve the logs.
;-)

![Jablotron_debug_all_packets](https://user-images.githubusercontent.com/44643774/155411183-57c478d5-8717-440d-a201-e1ec6903058e.png)

**Comment by kukulich** [comment]
Check the logs - we need to log lines with the problematic devices.

**Comment by RRobby** [comment]
@kukulich 
Good morning Jaroslav,
in attach logs grabbed from HA. I filtered only lines containg del following keyword and splitted in 3 different files ( hopefully useful for analysis)

- sensor.battery_level_of_motion_detector_device_XX.log    ( XX sersor from 29 to 34 )
- sensor.battery_level_of_outdoor_siren_device_12.log
- sensor.battery_load_voltage_of_outdoor_siren_device_12.log

Thaks
[sensor.battery_level_of_motion_detector_device_XX.log](https://github.com/kukulich/home-assistant-jablotron100/files/8131333/sensor.battery_level_of_motion_detector_device_XX.log)
[sensor.battery_level_of_outdoor_siren_device_12.log](https://github.com/kukulich/home-assistant-jablotron100/files/8131335/sensor.battery_level_of_outdoor_siren_device_12.log)
[sensor.battery_load_voltage_of_outdoor_siren_device_12.log](https://github.com/kukulich/home-assistant-jablotron100/files/8131336/sensor.battery_load_voltage_of_outdoor_siren_device_12.log)

**Comment by kukulich** [comment]
@RRobby I'm sorry these are not the logs I expected. I did not find any logs from the jablotron integration.

**Comment by RRobby** [comment]
@kukulich 
I inserted debug used in other thread hopping more usefull . I captured  (/config/home-assistant.log) and filtered only lines containg jablotron and/or DEBUG level. Thanks again Jaroslav
[Jablotron(home-assistant.log).txt](https://github.com/kukulich/home-assistant-jablotron100/files/8149483/Jablotron.home-assistant.log.txt)

**Comment by kukulich** [comment]
It looks your central unit does not report the battery states. There's a change it's reported in some other way but it's debuggable only with F-Link and Wireshark.
