### ISSUE TITLE
Jablotron failed to setup error after HA restart

### ISSUE THREAD

**Issue by RRobby** [kukulich/home-assistant-jablotron100#37]
Hi, 
after an HA restart,  Jablotron integration failed to inizialize itself . I've already noticed this behaviour in the past (after an HA restart) and I always solved simply disconnecting/connecting USB cable between my Raspberry Pi and Jablotron control unit.
Unfortunatly, yesterday I tried the same action, more times, without success , so , in this moment Jablotron integration is unusable. Is there a trick to solve this issue ( possibily without re-install the integration... I wouldn't want to reconfigure all related automations  )   
Below the error screenshot and logs. I hope in your help.
Thanks
![jablotron_error_log](https://user-images.githubusercontent.com/44643774/155896555-24e21b3d-22d4-4f43-875d-c0eeea120b96.png)
![jablotron_failed_to setup](https://user-images.githubusercontent.com/44643774/155896556-90e42ede-2d3c-4db6-a15f-6c42b52e7a30.png)
[jablotron_identify_port.txt](https://github.com/kukulich/home-assistant-jablotron100/files/8149287/jablotron_identify_port.txt)

**Comment by kukulich** [comment]
It’s probably caused by change of the serial port. You should check the port.

**Comment by RRobby** [comment]
Phisically I didn't change anything
In log provided before  you can see :

[39966.026462] usb 1-1.4: USB disconnect, device number 9
[39973.418886] usb 1-1.4: new full-speed USB device number 10 using xhci_hcd
[39973.526204] usb 1-1.4: New USB device found, idVendor=16d6, idProduct=0008, bcdDevice= 1.06
[39973.526234] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[39973.526243] usb 1-1.4: Product: JA-100 Flexi
[39973.526250] usb 1-1.4: Manufacturer: Jablotron ltd
[39973.526257] usb 1-1.4: SerialNumber: XXXXXXXXXXXXXXXXX
[39973.542976] hid-generic 0003:16D6:0008.0006: hiddev96,hidraw0: USB HID v1.11 Device [Jablotron ltd JA-100 Flexi] on usb-0000:01:00.0-1.4/input0
[39973.544326] usb-storage 1-1.4:1.1: USB Mass Storage device detected
[39973.549784] scsi host0: usb-storage 1-1.4:1.1
➜  ~ 
➜  ~ 
➜  ~ dmesg | grep hid
[39973.542976] hid-generic 0003:16D6:0008.0006: hiddev96,hidraw0: USB HID v1.11 Device [Jablotron ltd JA-100 Flexi] on usb-0000:01:00.0-1.4/input0

Kindly, What/where I shoud verify if the port is right and eventually how to modify it in Jablotron integration? Thank you

**Comment by kukulich** [comment]
It looks the right port is now `hidraw0` - you can check files in `.storage` HA folder - you can find there what port are you currently using.

**Comment by RRobby** [comment]
:-(
 Port seems  ok

➜  .storage more jablotron100
{
    "version": 2,
    "minor_version": 1,
    "key": "jablotron100",
    "data": {
        "/dev/hidraw0": {
            "devices": {
                "device_2": {
                    "connection": "wired",
                    "signal_strength": null,
                    "battery": false,
                    "battery_level": null,
                    "section": 1

**Comment by kukulich** [comment]
Try debug mode for the integration via HA "logger" integration.

**Comment by RRobby** [comment]
Activated debug as suggest you ...and after related HA ...all works properly ( i think to have place al least 10 restart during last 24h :-) . Anyway i don't think this is very stable situation, i notice this problem issue every time i restart HA. 
[Jablotron(home-assistant.log).txt](https://github.com/kukulich/home-assistant-jablotron100/files/8149474/Jablotron.home-assistant.log.txt)
