### ISSUE TITLE
Unknown device info type 21

### ISSUE THREAD

**Issue by matata86** [kukulich/home-assistant-jablotron100#41]
Ahoj, v logu mám neustále toto:

`Logger: custom_components.jablotron100
Source: custom_components/jablotron100/jablotron.py:2030
Integration: Jablotron 100 ([documentation](https://github.com/kukulich/home-assistant-jablotron100), [issues](https://github.com/kukulich/home-assistant-jablotron100/issues))
First occurred: 13. dubna 2022 15:03:50 (26 occurrences)
Last logged: 17:09:35

Unknown device info type 21: 0f00d52823d2af0101
Unknown device info type 21: 0f00d5282300000101`

Tušíš prosím, jak to odstranit?

**Comment by kukulich** [comment]
Try version 3.10.1 - There's should be probably more info in the log.

**Comment by MartinZapaPG** [comment]
Hi guys,
same here. 
HACS JA100 Integration 

Logger: custom_components.jablotron100
Source: custom_components/jablotron100/jablotron.py:2030 
Integration: Jablotron 100 (documentation, issues) 
First occurred: 19:02:29 (1 occurrences) 
Last logged: 19:02:29
Unknown device info type 21 (device 234): 900cea0a090f00d5640000000000

core-2022.5.4
Home Assistant OS 8.0
supervisor-2022.05.2

HACS
Integration version: 1.24.5

Jablotron 100+ 3.1.10

DEBUG:
2022-05-16 19:34:28 DEBUG (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Incoming (device 233): 900be90a080f00a60400000000
2022-05-16 19:34:28 DEBUG (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Incoming: d0089630843ff08ab34c

2022-05-16 19:34:29 DEBUG (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Incoming (device 234): 900cea0a090f00d5640000000000
2022-05-16 19:34:29 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Unknown device info type 21 (device 234): 900cea0a090f00d5640000000000

Any suggestions? Everithing is working fine only this message apears periodicaly every hour in the log. 

Thanks in advance.
Martin

**Comment by kukulich** [comment]
It will be not reported in next version.

**Comment by MartinZapaPG** [comment]
Many thanks for response and your information. Can I ask you, just to satisfy my curiosity what is the reason for this error message?

Pěkný den. 😉

Martin

**Comment by kukulich** [comment]
Released in 3.11.0.
