### ISSUE TITLE
USB + Security

### ISSUE THREAD

**Issue by mortenbpost** [kukulich/home-assistant-jablotron100#42]
Hi, 

Does HA need to be connected always by USB in order to use this extention?

In terms of security I'm worried to enter my master code or any code for that matter. Can you still receive some notification if you do not provide codes?

Thanks.

**Comment by kukulich** [comment]
> Does HA need to be connected always by USB in order to use this extention?

Yes.

> In terms of security I'm worried to enter my master code or any code for that matter. Can you still receive some notification if you do not provide codes?

Only sections can be checked and modified without admin password. However you still have to provide code during configuration.

**Comment by mortenbpost** [comment]
Thanks. I can't read anywhere of the potential security issues. Is the code sent to the cloud or?

**Comment by kukulich** [comment]
> Is the code sent to the cloud

No cloud - the communication is only via USB. Security depends on your HA security.
