### ISSUE TITLE
became unavailable

### ISSUE THREAD

**Issue by hajty626** [kukulich/home-assistant-jablotron100#44]
Hello,
after update to ver. 3.x few months ago, all devices come "Became unavailable" in about 10 min interval.

**Comment by kukulich** [comment]
You can try debug.

**Comment by hajty626** [comment]
Hello, I enable debug mode, but for now here is some errors from log. It can be problem with this:

This error originated from a custom integration.

Logger: custom_components.jablotron100
Source: custom_components/jablotron100/jablotron.py:2030
Integration: Jablotron 100 (documentation, issues)
First occurred: 08:21:34 (4 occurrences)
Last logged: 08:42:02

Unknown state packet (device 7): 5508a485c0014056a808
Unknown state packet (device 7): 5508a485c001307ae808
Unknown state packet (device 7): 5508a485c001607a0809
Unknown device info type 21 (device 234): 900cea0a090f00d54623d2af0101


This error originated from a custom integration.

Logger: custom_components.jablotron100
Source: custom_components/jablotron100/jablotron.py:1017
Integration: Jablotron 100 (documentation, issues)
First occurred: 10:12:14 (32 occurrences)
Last logged: 14:39:10

Read error: 'device_34'

**Comment by kukulich** [comment]
> Read error: 'device_34'

This is strange. Please enable `error` logging for Jablotron integration via `logger`.

**Comment by kukulich** [comment]
Or please find full log of your HA. It may be already logged.

**Comment by hajty626** [comment]
I have enabled debug mode, many lines are there.

**Comment by hajty626** [comment]
Hello,
these is only two error lines in debug log, device7 is show every few second, bud device34 every about 10 mins and the time is same when all devices are unavailable. It's 1st contact of magnet JA-150M, which i have disabled.

2022-05-20 15:25:43 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Unknown state packet (device 7): 5508a485c001b0660f0f
2022-05-20 15:48:50 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Read error: 'device_34'

**Comment by hajty626** [comment]
Device 7 is PIR JA-120PW, I have disabled in f-link device 34.

**Comment by kukulich** [comment]
Is there a trace in the log for `2022-05-20 15:48:50 ERROR (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Read error: 'device_34'` ?

**Comment by hajty626** [comment]
No I can't find it. But I solved it by change input 2 to input 1 on JA-150M an change from "Other" to "Flood detector" in HA. I have configured JA-150M as LD-81 (flood detection mode) and it was a problem probably. No error on device 34 is now.

Thank You to advise what can I looking for.

**Comment by kukulich** [comment]
Do I understand that you have no problem now?

**Comment by hajty626** [comment]
Yes, the device is no sending errors now and no became unavailable.
