### ISSUE TITLE
Blocking call warning in HA system logs

### ISSUE THREAD

**Issue by DarkWarden85** [kukulich/home-assistant-jablotron100#46]
Hi.

I sometimes get the following warning in my HA system logs:

`
Logger: homeassistant.util.async_
Source: util/async_.py:157
First occurred: 07:07:59 (1 occurrences)
Last logged: 07:07:59

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for jablotron100 doing blocking calls at custom_components/jablotron100/jablotron.py, line 332: time.sleep(1)
`
Home Assistant Version is 2022.06.4
Jablotron is version 3.11.1
Can this be fixed?
Also thanks again for the awesome integration.

**Comment by kukulich** [comment]
Probably fixed in https://github.com/kukulich/home-assistant-jablotron100/commit/ebfd7797089e432412b11ee62267e3ebd9310466

**Comment by kukulich** [comment]
Released in 3.11.2.
