### ISSUE TITLE
Key Fob - How to?

### ISSUE THREAD

**Issue by ruzickav** [kukulich/home-assistant-jablotron100#47]
Hello,
Integration is working well. How to use Key Fob? I have Key Fob in Peripherals, but see only one "button" in devices. This button is doing nothing (doesn't react on Key Fob pressing). My Key Fob has 4 buttons..... How to map it to HA?

Maybe some guid would be helpful.

Thanks in advance

**Comment by kukulich** [comment]
There's no support for "4 buttons keyfob" now. You can join the Discord, try to debug the keyfob via Wireshark and we may add the support.
