### ISSUE TITLE
Jablotron programable outputs

### ISSUE THREAD

**Issue by filipek92** [kukulich/home-assistant-jablotron100#5]
Is there any chance to make accessible control of programmable outputs? Can I help you with it?

**Comment by kukulich** [comment]
@filipek92 you can try to connect F-Link and sniff packets by Wireshark with USBCap.

**Comment by kukulich** [comment]
@filipek92 @fralitri @tomasbedrich If you can join our Discord and help to sniff the communication with Jablotron then we can probably prepare the support.

**Comment by fralitri** [comment]
Ok, i want help you. Can you explain me how I can do this

**Comment by kukulich** [comment]
Implemented in version 3.0.0 - to be released in a few days.
