### ISSUE TITLE
Jablotron100 connection failed – all sensors and devices are unavailable

### ISSUE THREAD

**Issue by Tomm206** [kukulich/home-assistant-jablotron100#51]
Hello,

I have a problem with connection of my Jablotron100 integration (since 24-08-22). All sensors and devices are unavailable. It always happens once or twice a day. Restart of HA usually doesn’t help.

![image](https://user-images.githubusercontent.com/95053956/186972534-6477c77d-8f59-4ee9-972a-13b7a8e7440c.png)

See the log below:

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/jablotron100/jablotron.py:457
Integration: jablotron100 (documentation, issues)
First occurred: 8:26:41 PM (1 occurrences)
Last logged: 8:26:41 PM

Error setting up entry Jablotron for jablotron100
Traceback (most recent call last):
  File "/config/custom_components/jablotron100/jablotron.py", line 453, in _detect_central_unit
    self._central_unit = reader.result(STREAM_TIMEOUT)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/jablotron100/jablotron.py", line 402, in reader_thread
    stream = self._open_read_stream()
  File "/config/custom_components/jablotron100/jablotron.py", line 1097, in _open_read_stream
    return open(self._config[CONF_SERIAL_PORT], "rb", buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/hidraw0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/jablotron100/__init__.py", line 22, in async_setup_entry
    await jablotron_instance.initialize()
  File "/config/custom_components/jablotron100/jablotron.py", line 271, in initialize
    self._detect_central_unit()
  File "/config/custom_components/jablotron100/jablotron.py", line 457, in _detect_central_unit
    raise ServiceUnavailable
custom_components.jablotron100.errors.ServiceUnavailable
`
`This error originated from a custom integration.

Logger: custom_components.jablotron100
Source: custom_components/jablotron100/jablotron.py:271
Integration: jablotron100 (documentation, issues)
First occurred: 8:26:41 PM (1 occurrences)
Last logged: 8:26:41 PM

[Errno 2] No such file or directory: '/dev/hidraw0'`

**Comment by kukulich** [comment]
I think the port is probably changing.

**Comment by Tomm206** [comment]
I did not change the usb port. I originally installed on "hidraw0". My Terminal & SSH shows:

![image](https://user-images.githubusercontent.com/95053956/186980275-ba35927d-a39f-45ea-bd0d-ba0944574883.png)

I am little bit confused. Any advise please? Jablotron intergration is key integration for me. Many automations rely on Jablotron integration. Thank you.

**Comment by kukulich** [comment]
Your operating system may change the port.

**Comment by Tomm206** [comment]
Operation system may have changed it. Then I dont understand why it works half a day and then it doesnt. Terminal & SSH shows "hidraw0" and "hidraw1". So I dont know which one is correct. I can try to change it in integration. Could you please advise me how to change it? Thank you.

**Comment by Tomm206** [comment]
Today the integration worked till 12:30 pm (from night restart). Then again all unavailable. Any idea please?

Can I just try to change the port here?
/config/custom_components/jablotron100/const.py

DEFAULT_SERIAL_PORT: Final = "/dev/hidraw0"

from hidraw0 to hidraw1?

Thank you.

**Comment by shakin89** [comment]
Try to look here, i had the same problem. 
https://discord.com/channels/733015709931536396/733015709931536399/878285665236844624
changing udev rules in your system may solve your problems.

**Comment by Tomm206** [comment]
> Try to look here, i had the same problem. https://discord.com/channels/733015709931536396/733015709931536399/878285665236844624 changing udev rules in your system may solve your problems.

How did you solve it? The link doesnt work. Thank you.

**Comment by ondrac91** [comment]
HI, same problem here, how do I change port name on OS layer? I am also not able change port in integration, I can fill port only when I install new integration.

**Comment by michaelscl** [comment]
Maybe crate file /etc/udev/rules.d/99-jablotron.rules
`SUBSYSTEM=="hidraw", SUBSYSTEMS=="usb", ATTRS{idVendor}=="16d6", ATTRS{idProduct}=="0008", SYMLINK+="jablotron"`

You can see all attributes by commnad:
`udevadm info --name=/dev/hidraw0 --attribute-walk`

**Comment by michaelscl** [comment]
> Maybe crate file /etc/udev/rules.d/99-jablotron.rules `SUBSYSTEM=="hidraw", SUBSYSTEMS=="usb", ATTRS{idVendor}=="16d6", ATTRS{idProduct}=="0008", SYMLINK+="jablotron"`
> 
> You can see all attributes by commnad: `udevadm info --name=/dev/hidraw0 --attribute-walk`



> > Try to look here, i had the same problem. https://discord.com/channels/733015709931536396/733015709931536399/878285665236844624 changing udev rules in your system may solve your problems.
> 
> How did you solve it? The link doesnt work. Thank you.

Maybe crate file /etc/udev/rules.d/99-jablotron.rules
`SUBSYSTEM=="hidraw", SUBSYSTEMS=="usb", ATTRS{idVendor}=="16d6", ATTRS{idProduct}=="0008", SYMLINK+="jablotron"`

You can see all attributes by commnad:
`udevadm info --name=/dev/hidraw0 --attribute-walk`
