### ISSUE TITLE
Add support for relay: JA-110N-DIN

### ISSUE THREAD

**Issue by petos** [kukulich/home-assistant-jablotron100#52]
Can you please add, as type of periferie(s), relay support (like JA-110N-DIN) as a switch?

**Comment by kukulich** [comment]
@petos Only if you can do the reverse engineering so we know how it works.

**Comment by petos** [comment]
@kukulich I'd love to do forward engineering and be more skilled there,... not mentioning reverse one...

**Comment by kukulich** [comment]
@petos Please try to connect me on Discord.

**Comment by petos** [comment]
@kukulich  As I'm not discord member, I'm unable to find you. However I've pinged you via linkedIn, just to init. the contact.

**Comment by kukulich** [comment]
@petos There's Discord channel here: https://github.com/kukulich/home-assistant-jablotron100#check
