### ISSUE TITLE
JA-106K-3G - Doesn't state status changes

### ISSUE THREAD

**Issue by marcocubi** [kukulich/home-assistant-jablotron100#54]
After the last update, status variations are not shown into HA

**Comment by kukulich** [comment]
Update of what? Your Jablotron? HA? Integration?

**Comment by marcocubi** [comment]
I updated to the last release the Jablotron integration on HA

**Comment by kukulich** [comment]
What version did you have before? There's no change about states in latest release.

**Comment by marcocubi** [comment]
I don't rember, but probably it was an ald version because I just updated HA from the release 2022.6

**Comment by marcocubi** [comment]
Looking at the registry, I have this issue:

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:160 
First occurred: 01:44:17 (8 occurrences) 
Last logged: 09:11:41

Error setting up entry Jablotron for alarm_control_panel
Error setting up entry Jablotron for binary_sensor
Error setting up entry Jablotron for sensor
Error setting up entry Jablotron for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 115, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 160, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

Have you any idea? I already reinstalled and reconfigured the integration but nothing changed

**Comment by kukulich** [comment]
Please try to find the complete log.

**Comment by marcocubi** [comment]
Where I can find it?
