### ISSUE TITLE
Indexa 9000 / JA-100K support

### ISSUE THREAD

**Issue by mareeekkkk** [kukulich/home-assistant-jablotron100#58]
Would it be possible to add the INDEXA 9000 Series to this integration? I guess its basically the same Hardware as the JA-100K, but different Firmware. 
I tested the connection, Indexa 9000 gets recognized as `hidraw0: USB HID v1.11 Device [Jablotron ltd JA-100 Flexi]`, but the Setup process stops at `Model of Jablotron not supported` in Home Assistant.

Thank you

**Comment by kukulich** [comment]
@mareeekkkk Please enable debug mode for jablotron integration and try it again. It should log some useful info.

**Comment by mareeekkkk** [comment]
Here's the Debug Output when i add the integration with /dev/hidraw0 and my Code.
`2022-12-14 14:34:08.668 DEBUG (ThreadPoolExecutor-2_0) [custom_components.jablotron100] Check serial port: 4007024a412d31344b0000100000000000000000dc290010000000000c0000000100000003d3000000000000680400100b0000006444001000000000b7560300`

**Comment by kukulich** [comment]
It looks it's reported as `JA-14K`, is it possible?

**Comment by kukulich** [comment]
You can try version from this branch: https://github.com/kukulich/home-assistant-jablotron100/tree/ja-14k

I've removed one check so we will see if it works or not.

**Comment by mareeekkkk** [comment]
I just tried this branch. It works, the Indexa9000 adds into HomeAssistant just fine and i can see motion being detected. 
I will try different functions in the next days and give you feedback about the functionality. 
Thank you very much!

**Comment by kukulich** [comment]
@mareeekkkk ok, i can make the support than official.

**Comment by mareeekkkk** [comment]
Just a quick update. Everything is working, i can control all features of the JA-14k from homeassistant and it runs stable.

**Comment by kukulich** [comment]
Ok, the oficial support will be part of the next release.
