### ISSUE TITLE
home assistant login events fill event log

### ISSUE THREAD

**Issue by leo-b** [kukulich/home-assistant-jablotron100#59]
Currently my alarm system (JA-107K) logs a login event every 35 seconds, which makes it very hard to find other events when browsing events on the keypad.

Is one login every 35 seconds the normal behavior?
Is there a way to maybe keep the connection open for a longer time to reduce the number of events?
Do you know if it is possible to suppress logging of authorization events by configuration on the control panel?

Cheers,
--leo

**Comment by kukulich** [comment]
Integration mimics the behaviour of F-Link so it has to send login events often to keep the connection open.
