### ISSUE TITLE
Cannot install on 0.118.2

### ISSUE THREAD

**Issue by ulfendk** [kukulich/home-assistant-jablotron100#6]
I was happily using an older version of this integration.  As it stated I had to re-install it instead of upgrading, I did.  Unfortunately, it does not work now.

I enter the port, pin and units.  The resulting integration in HA has no entities and I get the following error in the log:

```
Logger: homeassistant.config_entries
Source: custom_components/jablotron100/jablotron.py:556
First occurred: 14.18.58 (1 occurrences)
Last logged: 14.18.58

Error setting up entry Jablotron for jablotron100
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/jablotron100/__init__.py", line 27, in async_setup_entry
    await jablotron.initialize()
  File "/config/custom_components/jablotron100/jablotron.py", line 287, in initialize
    self._detect_devices()
  File "/config/custom_components/jablotron100/jablotron.py", line 556, in _detect_devices
    devices_info_packets = reader.result(estimated_duration * 2)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 441, in result
    raise TimeoutError()
concurrent.futures._base.TimeoutError
```

Any help would be appreciated :)

Thank you for making this integration!

**Comment by kukulich** [comment]
@ulfendk how many devices do you have?

It looks it fails in new feature added in 2.2.0. Can you try 2.1.1 ?

**Comment by ulfendk** [comment]
Hi @kukulich, I just pulled it from HACS, so I would assume that it is 2.2.0?

Also, I have 14 devices.

**Comment by kukulich** [comment]
Hmm, 14 devices is not so much... So the timeout is strange. What type of Jablotron central device do you have? The new feature is tested mostly on JA-101 so there may be some problems on different type...

You can choose version in HACS. I expected that 2.1.1 should work for you.

![Clipboard01](https://user-images.githubusercontent.com/260445/99878916-f6fbf500-2c08-11eb-90a9-ce92e69a7149.png)

**Comment by ulfendk** [comment]
Downgrading to 2.1.1 worked

**Comment by kukulich** [comment]
@ulfendk Did you use code of administrator during the installation?

**Comment by ulfendk** [comment]
Nope, I use a dedicated account, so the Jablotron app reports correctly.

**Comment by kukulich** [comment]
@ulfendk Ok, it makes sense now. You need "administrator" account to make sensors working. You can use dedicated account but it has to be administrator.

**Comment by ulfendk** [comment]
Ok, I will check on that.

Any chance you will add support for the RS-485 interface, so I can move my HA back down into the basement?

**Comment by ulfendk** [comment]
But the PIR sensors do work in the old version.

**Comment by kukulich** [comment]
> Any chance you will add support for the RS-485 interface

No, I'm not planing it.

**Comment by kukulich** [comment]
@ulfendk 

> Ok, I will check on that.

Any news?

**Comment by ulfendk** [comment]
Yes, I updated the user to Administrator and it worked after the upgrade 👍 Thank you for creating this integration.

**Comment by kukulich** [comment]
Perfect!
