### ISSUE TITLE
Unable to trigger alarm from an automation

### ISSUE THREAD

**Issue by PereViader** [kukulich/home-assistant-jablotron100#64]
Is it possible to trigger an alarm from an automation?

Use case: we have a Google nest camera and wish to use their presence sensing functionality to trigger the alarm. 

However using the  alarm trigger service

```
service: alarm_control_panel.alarm_trigger 
```

With the appropriate code and entity/device reports that they are not compatible with the service.

Is this something that could be added to the integration?

**Comment by kukulich** [comment]
We were not able to find the way how to do it.

**Comment by PereViader** [comment]
Thank you for the quick response. 
That's really unfortunate, as it is working great!
Will try to look for another way to trigger it and send a message here if I find anything.
Feel free to close this issue
