### ISSUE TITLE
Question - Motion Detector - presence check

### ISSUE THREAD

**Issue by jarojetu** [kukulich/home-assistant-jablotron100#65]
Hi, this is more like a question than issue. For "Motion Detector" is there any way how to get an even / read the state in case the area is disarmed and i woul like to check just the presence of someone in the room (and potentionaly trigger some other events)?

Thanks!

**Comment by kukulich** [comment]
It works this way by default.

**Comment by jarojetu** [comment]
Thanks for swift response - I now understand the reson ... I think there is some issue on my side.
I have five motion sensors and only one detecting this motions. Other despite the fact all of them working correctly - I cannto see the activity in HA like for the one below.
Any idea what can i have wrong please?

![image](https://user-images.githubusercontent.com/17701406/219963793-ae3c5856-b35b-4b1f-8d92-1c42549767ed.png)

**Comment by kukulich** [comment]
You can try debug - see readme.

**Comment by jarojetu** [comment]
Thanks for hint, in logs i believe that events are generated correctly:

2023-02-19 19:21:03.982 DEBUG (ThreadPoolExecutor-2_0)
[custom_components.jablotron100] Incoming (device 2): 5508007180003053541e
2023-02-19 19:21:06.006 DEBUG (ThreadPoolExecutor-2_0)
[custom_components.jablotron100] Incoming: 800d0cffffffff0700078008200100
2023-02-19 19:21:06.006 DEBUG (ThreadPoolExecutor-2_0)
[custom_components.jablotron100] Incoming: 5203820113
2023-02-19 19:21:06.508 DEBUG (ThreadPoolExecutor-2_0)
[custom_components.jablotron100] Incoming: d008966c823f5f53740d

But I still cannot see them in HA Logbook and there is nothing more in logs
which might guide me where the issue is...

ne 19. 2. 2023 v 18:31 odesílatel Jaroslav Hanslík ***@***.***>
napsal:

**Comment by jarojetu** [comment]
I found the issue, the device mapping in configuration - i just did it randomly which is obviously silly thing. So now the mapping is correct and it is working as expected - thanks.
![image](https://user-images.githubusercontent.com/17701406/219971888-562d090e-d476-4e81-848c-8365d3fb2ad8.png)
