### ISSUE TITLE
LAN config

### ISSUE THREAD

**Issue by fralitri** [kukulich/home-assistant-jablotron100#7]
Good morning,
I need to now how to configure the integration for connecting via Lan at a JA 101K-LAN
Thank you

**Comment by kukulich** [comment]
@fralitri I'm sorry I don't understand you. The integration does not work via LAN connection. You need to connect your JA 101L-LAN via USB cabel to the server with your HA..

**Comment by fralitri** [comment]
In release 2.0.0:
Added LAN connection sensor if central unit is connected via LAN - Only JA-101K-LAN supported currently

**Comment by kukulich** [comment]
@fralitri It's sensor that check LAN connection of you central unit but the integration works on USB cabel.

**Comment by fralitri** [comment]
Ok, now I understand. Thank you
