### ISSUE TITLE
Can't arm for the night...

### ISSUE THREAD

**Issue by Kozze** [kukulich/home-assistant-jablotron100#74]
Hi there,
I have connected my HA to my Jablotron 100 alarm installation and it has worked well for approx. 4 months.
Recently I noticed that arming for the night no longer work true HA. (maybe After an HA update, I'm not sure?)
However, fully arming and disarming the alarm works.
When I manually arm true the Jablotron keypad for the night, I can disable it via HA.
The options “arm_night” and “arm_away “are enabled in the UI Keypad of HA.

What could be wrong here?
Best regards, Benny

**Comment by kukulich** [comment]
Please look at integration options - there’s new settings that may cause this - see release notes.

**Comment by Kozze** [comment]
> Please look at integration options - there’s new settings that may cause this - see release notes.

Hi,
Thank you for your quick reply.
I showed but cannot find what I should do, everything seems OK
Can you please point me in the direction I should look?
Thanks, Benny

**Comment by Kozze** [comment]
OK, I got one step further...

When both options are checked," Code required to arm" & "Code required to disarm", I **CANNOT** arm for the night.

When only the option Code required to disarm" is checked, I can arm the alarm for the night without entering a code AND disarming must be done with a code.

I assume something is going wrong when the "Code required to arm" option is enabled.

**Comment by kukulich** [comment]
Fixed in latest version.

**Comment by Kozze** [comment]
Thank you for the change, it works again !
