### ISSUE TITLE
Thermostat and head

### ISSUE THREAD

**Issue by fralitri** [kukulich/home-assistant-jablotron100#8]
Good morning, the integration is working whith 150TP, 111TH, 150N-HEAD and PG output?

**Comment by kukulich** [comment]
150TP, 111TH, 150N-HEAD: Probably no, because they probably have more states than active/inactive.

PG output: https://github.com/kukulich/home-assistant-jablotron100/issues/5

**Comment by fralitri** [comment]
I ask this because I have that components in my system
