### ISSUE TITLE
ELECTRIC_CURRENT_MILLIAMPERE ; ELECTRIC_POTENTIAL_VOLT params will no longer be supported

### ISSUE THREAD

**Issue by palota324** [kukulich/home-assistant-jablotron100#85]
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: 15. ledna 2024 v 10:57:35 (2 occurrences)
Last logged: 15. ledna 2024 v 10:57:35

ELECTRIC_CURRENT_MILLIAMPERE was used from jablotron100, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.MILLIAMPERE instead, please create a bug report at https://github.com/kukulich/home-assistant-jablotron100/issues
ELECTRIC_POTENTIAL_VOLT was used from jablotron100, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please create a bug report at https://github.com/kukulich/home-assistant-jablotron100/issues

**Comment by kukulich** [comment]
@palota324 You don't use the latest version of integration.
