### ISSUE TITLE
Bezdrátový detektor rozbití skla pro CA2103 ja-180B

### ISSUE THREAD

**Issue by palota324** [kukulich/home-assistant-jablotron100#86]
Hello. Sensor is visible in HA, reports device status, battery status, alarm detection, except battery capacity. The entity is presented in the system, but with a question mark as unavailable. Thank you in advance for the answer or solution.

**Comment by kukulich** [comment]
I don't understand. `reports device status` vs `but with a question mark as unavailable` - it does not make sense to me
