### ISSUE TITLE
Disarm not recognizing different users

### ISSUE THREAD

**Issue by tomasbedrich** [kukulich/home-assistant-jablotron100#9]
I do have 3 users in my Jablotron central unit:

- Service
- Admin
- Non-admin

When I install the integration using Service user passcode, then only that user's passcode is working to Disarm sections.

When I use passcode of either Admin or Non-admin user for disarming, everything seems good in HA (section green), but the Section is not really disarmed.

I know it worked previously, but I haven't used it for a while. Yesterday I did an update from Docker based HA installation to Home Assistant OS, therefore I wanted to test all the integrations and found this.

There is unfortunately nothing relevant in my logs.

**Comment by kukulich** [comment]
You should not use "service" user passcode to install the integration. Use the "admin" user.

However I can confirm that the "user" (non-admin) code cannot disarm section that is armed by "admin" user but I'm not sure if it can be solved...

**Comment by tomasbedrich** [comment]
Thanks for a suggestion regarding installation. I tried installation using Admin user passcode too, but the result is similar: in that case both Admin and Non-admin users were able to arm a section, but only Admin was able disarm it.

In a nutshell: I understand the limitation that Non-admin cannot disarm sections armed by Admin. What is surprising to me is that Non-admin cannot disarm the section he arms previously (in none of the installation methods mentioned above).

**Comment by kukulich** [comment]
@tomasbedrich Are you able to sniff packets with WireShark?

**Comment by tomasbedrich** [comment]
I do have some experience reverse-engineering network protocols, but not USB ones. What communication you interested in?

**Comment by kukulich** [comment]
@tomasbedrich It would be easier if you can connect to Discord https://github.com/kukulich/home-assistant-jablotron100/ :)

**Comment by kukulich** [comment]
It should be fixed in release 2.4.0 or 3.0.0.

It works in my testing version now :)
