### ISSUE TITLE
Asterisk not showing

### ISSUE THREAD

**Issue by RedwoodNL** [kukulich/home-assistant-jablotron100#90]
Using Jablotron with prefixes so for example:   4*9999 as codes. No matter what i do, no * will be on the keypad. 
I've entered the master code with asterisk in the configuration.

**Comment by kukulich** [comment]
What keypad do you see? Can you post a screenshot?

**Comment by RedwoodNL** [comment]
![IMG_8676](https://github.com/kukulich/home-assistant-jablotron100/assets/123517690/d45750b5-48bd-4604-bc72-cef65b8a176c)
Sure!

**Comment by kukulich** [comment]
The detection is here: https://github.com/kukulich/home-assistant-jablotron100/blob/6220840e1f844646e4383468b8f9d29f14e6e6b0/custom_components/jablotron100/jablotron.py#L273

I cannot test is it so you can change it here to check where’s the problem.

**Comment by RedwoodNL** [comment]
Sorted! Reinstalled it. Not sure what was wrong tho. Thanks
