### ISSUE TITLE
Arming requires a code but none was given

### ISSUE THREAD

**Issue by Dehumanizer77** [kukulich/home-assistant-jablotron100#93]
Suddenly, my alarm started to fail arming with this error. Integration version 3.24.1, HS version 2024.6.0
I think this started after upgrading HA to 2024.6.0

I don't have arming with code, so I don't understand the error. Require code for arming is not set In settings, and curiously, disarming (which requires a code) works perfectly.

**Comment by Dehumanizer77** [comment]
update: with 3.25 even disarming does not work (but no error, it appears if it was disarmed but it's not)

**Comment by Dehumanizer77** [comment]
,ok, so after reload it's the same, disarming works, arming requires a code, wvwn if the code is set in configuration

**Comment by Dehumanizer77** [comment]
actuually, sorry, it's the opposite, arming works but disarming dies not and wants the code, which is already set in configuration, so automations don't work

**Comment by kukulich** [comment]
I think this is expected behaviour because od the new HA feature: “default codes”

**Comment by Dehumanizer77** [comment]
How does it work? So what should I set so that it will work as before?

**Comment by Dehumanizer77** [comment]
Ok when I disabled "require code for disarming" it works as before now.

**Comment by Dehumanizer77** [comment]
Ok when I disabled "require code for disarming" it works as before now.
