### ISSUE TITLE
Jablotron integration stops updating after a while

### ISSUE THREAD

**Issue by RGB666** [kukulich/home-assistant-jablotron100#94]
I have a problem with the Jablotron integration: it stops updating after a while. Each morning, the integration does not update a changing arm/disarm or PG status. However, the status suddenly updates later in the day. What could be causing this?

**Comment by Sartenovi** [comment]
I have the same problem.  I tested all the possibilities that are in my power, but nothing worked.  I have to restart HA twice daily.  for now this integration is unusable.

**Comment by Sartenovi** [comment]
small things separated them, because communication breaks down completely.  does not work until HA restart

**Comment by RGB666** [comment]
I am running HA on proxmox server (mini PC)

**Comment by kukulich** [comment]
I don't have any problem on HaOS so I expect it is a problem in virtualization settings.

**Comment by RGB666** [comment]
It looks like my Jablotron-HA communication stops during the night. As all other HA communication have no problems during the night and the Jablotron is connected by a USB port, I have the feeling the USB port goes into a sort of standby/sleep/hibernation mode.(it's or a he usb or the Jablotron hardware itself)
I am running HA on a proxmox server. Who can help me debugging my system? How can I check /ebug the USB port communication settings?

**Comment by stewe12** [comment]
I have the same problem since my installation technic updated Jablotron main unit to the latest version firmware. When Jablotron sends some pointless SMS with battery status, it also changes /dev/hidraw0 to /dev/hidraw1 or the other way. I need to go to integrations and reconfigure the integration. Really annoying feature of the Jablotrons new update.

**Comment by woodrook** [comment]
Same problem for me since first jablotron integration more than one year ago......randomly integration status change to "unavailable"

I don't no why but I use spook to detect "unavailable" status and reload the integration.

It's a workaroud but it works well. Despite this a fix would be better

**Comment by kukulich** [comment]
@woodrook The problem is probably in your installation, not in the integration.

**Comment by woodrook** [comment]
May be but i don't thik so, i've just enabled debug logging

**Comment by RGB666** [comment]
Still have the problem as many others.

**Comment by mkapusnik** [comment]
I encountered the same issue when I moved my HA installation to RPi5 (running in docker on top of raspbian bookworm). Port started to randomly switch between /dev/hidraw0 and /dev/hidraw1. Everytime this changed, integration stopped responding.
Previously, I was running it on RPi4 (docker, bullseye) and it was rock stable.
I came up with a workaround to spin up HAOS on some older RPi3 and propagated the sensors through "Remote HA" addon to my main instance. Kinda weird setup, I know, but worked reliably.
There was no change of the jablotron firmware that I know of, so it does seem somehow related to the underlying system/hw.

Anyway, I updated to recently released 3.26.0 and gave it another try on RPi5 (docker,bookworm). Running stable for about two days now, looks promising.

**Comment by andyboeh** [comment]
You can easily work around changing serial ports by a udev rule that creates a persistent symlink. Mine looks like this:

```
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="16d6", ATTRS{idProduct}=="0008", MODE="0666", SYMLINK+="hidjablotron"
```

My integration is pointed to `/dev/hidjablotron` and the name persists, even if the kernel decides to change `/dev/hidraw0` to `/dev/hidraw1` or vice-versa.

@kukulich The README could be improved by adding this information / the udev rule.

**Comment by stewe12** [comment]
As I am not able to create udev on my installation, so I did @woodrook workaround when I am monitoring few sensors and if they are unavailable for 5 seconds, I reload Jablotron. It works really great. Props to @woodrook as it was perfectly reliable workaround for last 3 weeks.

**Comment by mkapusnik** [comment]
The udev rule is definitely a good tip. However, in my case the root cause seems to come from using "privileged: true" for docker container, which mirrors the attached devices during the start of the container, but never updates them. Therefore HA didn't see the symlink's target.
I'm still seeing integration getting stopped after some time (even several days), though :/.
