### ISSUE TITLE
Arming stopped working

### ISSUE THREAD

**Issue by fxxer** [kukulich/home-assistant-jablotron100#95]
Last few day arming stopped working. I had it set not to require code to arm (as before) and it stopped working and have this error:
`Failed to call service alarm_control_panel/alarm_arm_away. Validation error: Arming requires a code but none was given for alarm_control_panel.section_3`

Was there any change in integration?  Admin code is set as before, I did not change it lately. Thanks

If I turn to require code to arm, it is working. But before the code entered during setup was enough.

**Comment by kukulich** [comment]
You have to set default code for the section - that’s new HA feature

**Comment by fxxer** [comment]
Thanks, I was not aware of this change
