### ISSUE TITLE
Sliding Door icon's

### ISSUE THREAD

**Issue by Mighty5nake** [kukulich/home-assistant-jablotron100#98]
Hi,

i'm still learning the ropes in HA but i'm wondering if you could add the posibilty to select a sliding door (Open/Closed) , the mdi is present in HA but i can only select door or window for the moment for the entity.

or am i missing something ?

Regards

![image](https://github.com/user-attachments/assets/0956809d-af42-415e-a4dd-aec5eef5ae29)

**Comment by kukulich** [comment]
This feature is part of the HA itself, so it has to be add to HA.
