### ISSUE TITLE
JA-103K - VMWare USB problem

### ISSUE THREAD

**Issue by chobott** [kukulich/home-assistant-jablotron100#99]
Hello, after upgrade from JA-101K to JA-103K hardware, VMWare stop working USB bridge into my HAOS instance.

After connect USB to ESXi there is " JABLOCOM s.r.o. product 0x0008 " device, when i start VMs system doesnt run with connected USB info VM. When disconnect USB from Jablotron i Can start VM without problem.

Is there somebody with same problem?

Intel NUC + ESXi 7 with latest update

T.

**Comment by andyboeh** [comment]
Maybe your VM tries to boot from USB?

**Comment by chobott** [comment]
Hmmm i can try disable boot from USB but with JA-101K working in this same configuratiom without problem
